export const DISTRICT_SELECT_OPTIONS: { value: string; label: string }[] = [
    { value: "viana_do_castelo", label: "Viana do Castelo" },
    { value: "braga", label: "Braga" },
    { value: "porto", label: "Porto" },
    { value: "vila_real", label: "Vila Real" },
    { value: "braganca", label: "Bragança" },
    { value: "aveiro", label: "Aveiro" },
    { value: "viseu", label: "Viseu" },
    { value: "guarda", label: "Guarda" },
    { value: "coimbra", label: "Coimbra" },
    { value: "castelo_branco", label: "Castelo Branco" },
    { value: "leiria", label: "Leiria" },
    { value: "santarem", label: "Santarém" },
    { value: "lisboa", label: "Lisboa" },
    { value: "portalegre", label: "Portalegre" },
    { value: "setubal", label: "Setúbal" },
    { value: "evora", label: "Évora" },
    { value: "beja", label: "Beja" },
    { value: "faro", label: "Faro" },
]
